# Copyright 2019-2020 Hewlett Packard Enterprise Development LP

# Dockerfile for testing HMS BMC NW protocol pkg.

FROM cray/hms-bmc-networkprotocol-build-base

# Run any tests that might be present.
RUN set -ex \
    && go test -v stash.us.cray.com/HMS/hms-bmc-networkprotocol/pkg/.
